__title__ = "FreeCAD geant4 mass model creator"
__author__ = "Hualin Xiao (hualin.xiao@psi.ch) "
__url__ = "http://polar.psi.ch"
import FreeCAD
import FreeCADGui


class GDML(Workbench):

    MenuText = "g4cad"
    ToolTip = "g4cad - a Geant4 mass model creator"
    Icon = """
/* XPM */
static char *_c2f5c2915484604c2a3458ab27f4644wNGoqE062hGasR80[] = {
/* columns rows colors chars-per-pixel */
"183 92 142 2 ",
"   c #0D47A1",
".  c #0F48A2",
"X  c #1049A2",
"o  c #144CA4",
"O  c #154DA4",
"+  c #1850A5",
"@  c #1C53A7",
"#  c #1D53A7",
"$  c #1F55A8",
"%  c #2257A9",
"&  c #2458AA",
"*  c #275AAB",
"=  c #285BAB",
"-  c #295CAC",
";  c #295DAC",
":  c #2C5FAD",
">  c #2D60AE",
",  c #2F61AE",
"<  c #3062AF",
"1  c #3263AF",
"2  c #3364B0",
"3  c #3666B1",
"4  c #3767B1",
"5  c #3867B2",
"6  c #3A69B2",
"7  c #3B6AB3",
"8  c #3C6BB3",
"9  c #3D6CB4",
"0  c #3E6DB4",
"q  c #426FB6",
"w  c #4370B6",
"e  c #4672B7",
"r  c #4773B7",
"t  c #4874B8",
"y  c #4974B8",
"u  c #4D77BA",
"i  c #4E79BA",
"p  c #507ABB",
"a  c #537CBC",
"s  c #567FBD",
"d  c #577FBE",
"f  c #5880BE",
"g  c #5981BE",
"h  c #5B82BF",
"j  c #5C83C0",
"k  c #5F85C1",
"l  c #6186C1",
"z  c #6187C2",
"x  c #6389C3",
"c  c #6489C3",
"v  c #658AC3",
"b  c #678CC4",
"n  c #688CC4",
"m  c #6A8EC5",
"M  c #6E91C7",
"N  c #6F91C7",
"B  c #7092C7",
"V  c #7193C8",
"C  c #7394C8",
"Z  c #7395C9",
"A  c #7596CA",
"S  c #7798CA",
"D  c #7A9ACB",
"F  c #7B9BCC",
"G  c #7C9BCC",
"H  c #7D9CCC",
"J  c #819FCE",
"K  c #82A0CE",
"L  c #85A2CF",
"P  c #86A3D0",
"I  c #87A4D1",
"U  c #88A5D1",
"Y  c #8CA8D2",
"T  c #8EA9D3",
"R  c #90ABD4",
"E  c #91ABD4",
"W  c #93ADD5",
"Q  c #94ADD5",
"!  c #97B0D6",
"~  c #98B0D7",
"^  c #99B1D7",
"/  c #99B2D8",
"(  c #9AB3D8",
")  c #9CB4D9",
"_  c #9DB5D9",
"`  c #9EB5D9",
"'  c #A0B7DA",
"]  c #A1B8DB",
"[  c #A4BADC",
"{  c #A6BBDC",
"}  c #A7BCDD",
"|  c #A9BDDD",
" . c #ABC0DF",
".. c #ADC1DF",
"X. c #AEC2E0",
"o. c #B0C3E0",
"O. c #B2C5E1",
"+. c #B6C7E3",
"@. c #B7C8E3",
"#. c #B9CAE4",
"$. c #BACAE4",
"%. c #BBCBE4",
"&. c #BCCCE5",
"*. c #BDCCE5",
"=. c #BFCFE6",
"-. c #C0CFE7",
";. c #C2D1E7",
":. c #C3D2E8",
">. c #C5D3E9",
",. c #C7D4E9",
"<. c #CAD7EA",
"1. c #CBD7EB",
"2. c #CDD9EB",
"3. c #CFDAEC",
"4. c #D0DBED",
"5. c #D3DEEE",
"6. c #D4DFEE",
"7. c #D6E0EF",
"8. c #D7E1F0",
"9. c #D9E2F0",
"0. c #DBE4F1",
"q. c #DCE4F1",
"w. c #DFE6F2",
"e. c #E0E7F3",
"r. c #E1E8F3",
"t. c #E3EAF4",
"y. c #E4EBF5",
"u. c #E5ECF5",
"i. c #E7EDF6",
"p. c #E9EEF7",
"a. c #EBF0F7",
"s. c #ECF1F8",
"d. c #EEF2F8",
"f. c #EFF3F9",
"g. c #F0F3F9",
"h. c #F2F5FA",
"j. c #F3F6FA",
"k. c #F6F8FB",
"l. c #F7F9FC",
"z. c #F8FAFC",
"x. c #FBFCFE",
"c. c white",
/* pixels */
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                        . .                   ",
"                                                                                                                                                                                                                                                                                                                                                  K P P P I +                 ",
"                                                                                                                                                                                                                                                                                                                                                . l.c.c.c.c.- .               ",
"                                                                                                                                                                                                                                                                                                                                                . l.c.c.c.c.- .               ",
"                                                                                                                          X 6.c.c.c.c.7.                                                                                                                                                                                                          k.c.c.c.c.- .               ",
"                                                                                                                          E c.c.c.c.c.7.                                                                                                                                                                                                      . . k.c.c.c.c.- .               ",
"                                                                                                                      . r c.c.c.c.c.c.7.                                                                                                                                                                                                          z.c.c.c.c.: .               ",
"                                                                                                                      # i.c.c.c.c.c.c.7.                                                                                                                                                                                                          z.c.c.c.c.-                 ",
"                                                                                                                      ..c.c.c.c.c.c.c.7.                                                                                                                                                                                                          z.c.c.c.c.-                 ",
"                                                                                                                    v c.c.c.q.d.c.c.c.7.                                                                                                                                                                                                          z.c.c.c.c.: .               ",
"                                                                                                                  - h.c.c.c.x r.c.c.c.7.                                                                                                                                                                                                          z.c.c.c.c.-                 ",
"                                                                                                                . ,.c.c.c.7.. d.c.c.c.7.                                                                                                                                                                                                          z.c.c.c.c.-                 ",
"                                                                                                                L c.c.c.c.a   z.c.c.c.7.                                                                                                                                                                                                          z.c.c.c.c.: .               ",
"                                                                                                              q z.c.c.c.O.. X c.c.c.c.7.                                                                                                                                                                                                          z.c.c.c.c.-                 ",
"                                                                                                            O q.c.c.c.a.%   O c.c.c.c.7.                                                .                                                           .     . .   . .                                                               .               k.c.c.c.c.-                 ",
"                                  O q x S K J S x t #                                                       ' c.c.c.c.a     * c.c.c.c.7.                                            . 1 g N H K A v r %                                       O r h N H H B x 6 X .                                                 X r v F K Z x 6 .     .       k.c.c.c.c.: .               ",
"                            O m >.z.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.F                           . g c.c.c.c.)       - c.c.c.c.7.                                      . z ..h.c.c.c.c.c.c.c.c.c.t.` p                         X t ^ 5.c.c.c.c.c.c.c.c.c.l.*.j X                                         p O.l.c.c.c.c.c.c.c.s.} 6 .     . s.c.c.c.c.-                 ",
"                      .   x i.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.F                           * s.c.c.c.6.o       > c.c.c.c.7.                                  . N i.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.o.                  : Q s.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.6.6                                   3 ,.c.c.c.c.c.c.c.c.c.c.c.c.c.| #   . i.c.c.c.c.:                 ",
"                      . ] c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.D                           @.c.c.c.z.6 .       , c.c.c.c.7.                                * 1.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.N                 t c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.z.p                               k k.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.r.3   5.c.c.c.c.: .               ",
"                      ` c.c.c.c.c.c.1.I k i s m ` a.c.c.c.c.c.c.c.h.6.#.` K 3                         A c.c.c.c.D           , c.c.c.c.7.                              5 i.c.c.c.c.c.c.c.c.c.k.h.c.c.c.c.c.c.z.#                 O p.c.c.c.c.c.c.i.*...` ] *.g.c.c.c.c.c.c.s.-                           v c.c.c.c.c.c.c.c.r.1.*.4.i.c.c.c.c.c.d.> ;.c.c.c.c.-                 ",
"                    k c.c.c.c.c.y.t               O L c.c.c.c.c.W                                   3 l.c.c.c.*.            1 c.c.c.c.7.                            = i.c.c.c.c.c.c.*.m 1 . .   X 3 x ` q.c.O.                    P c.c.l.O.v -             . g 8.c.c.c.c.c.[                         r l.c.c.c.c.c.i.Z %           - N 0.c.c.c.5.;.c.c.c.c.-                 ",
"                . . q.c.c.c.c.i.*                     m c.c.c.c.z.>                           . . X 5.c.c.c.s.-             > c.c.c.c.7.                          . 1.c.c.c.c.c.7.q     .   .   . .   . . 8 3                     * 3.B +                       O ;.c.c.c.c.x.*                     O e.c.c.c.c.c...+               .   O U c.c.c.c.c.c.c.c.:                 ",
"                  i c.c.c.c.c.g                         #.c.c.c.c.^ . .                           W c.c.c.c.g . .           1 c.c.c.c.7.                          A c.c.c.c.c.;.O                                                                                 % h.c.c.c.c.v                     H c.c.c.c.c.#.X .                     . T c.c.c.c.c.c.c.-                 ",
"                  Q c.c.c.c.r..                         s c.c.c.c.d..                           u c.c.c.c.]                 > c.c.c.c.7.                        O a.c.c.c.c.r.+ .                                                                                   ] c.c.c.c.`                 . . p.c.c.c.c.a.+                         . X 8.c.c.c.c.c.c.>                 ",
"                  ;.c.c.c.c.[ .                         # c.c.c.c.c.6 .                       @ r.c.c.c.q.+                 > c.c.c.c.7.                        N c.c.c.c.c.i .                                                                                     x c.c.c.c.*.                . g c.c.c.c.c.A                               g c.c.c.c.c.c.>                 ",
"                  q.c.c.c.c.L                             h.c.c.c.c.s .                     . ..c.c.c.c.w .                 > c.c.c.c.7.                        ;.c.c.c.c.2.                                                                                      . 0 c.c.c.c.3.                  [ c.c.c.c.h.O                               . s.c.c.c.c.c.-                 ",
"                  i.c.c.c.c.S                             i.c.c.c.c.x                       v c.c.c.c.K                     1 c.c.c.c.7.                      + z.c.c.c.c.B .                                                                                       1 c.c.c.c.q.                  r.c.c.c.c.|                                   | c.c.c.c.c.- .               ",
"                  0.c.c.c.c.L                           . h.c.c.c.c.f                     > h.c.c.c.,..                     > c.c.c.c.7.                      i c.c.c.c.c.*                                                                                         * c.c.c.c.e.                $ c.c.c.c.c.x X                                 N c.c.c.c.c.- .               ",
"                  *.c.c.c.c. .                          * c.c.c.c.c.6 .                 . 1.c.c.c.h.-                       > c.c.c.c.7.                    . A c.c.c.c.p..                                                                         . .             = c.c.c.c.t.                r c.c.c.c.c.3                                   r c.c.c.c.c.- .               ",
"                . I c.c.c.c.s.O                         N c.c.c.c.d.. .                 L c.c.c.c.x .                       1 c.c.c.c.7.                    . Q c.c.c.c.;.                                                                0 C ` -.7.a.z.z.c.c.c.c.c.c.c.c.c.c.t.                k c.c.c.c.c.X                                   % c.c.c.c.c.> .               ",
"                  1 c.c.c.c.c.J                     . O 0.c.c.c.c.[                   q x.c.c.c...X .                       > c.c.c.c.7.                      ..c.c.c.c.| .                                                         3 ^ a.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.e.                A c.c.c.c.p.                                    . c.c.c.c.c.- .               ",
"                . . #.c.c.c.c.c.k                   O O.c.c.c.c.z.>                 + q.c.c.c.r.O                           1 c.c.c.c.7.                      +.c.c.c.c.^ .                                                     # [ c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.t.                H c.c.c.c.0.                                      c.c.c.c.c.= .               ",
"                    1 h.c.c.c.c.c.| 8 .         O z 7.c.c.c.c.c.I                   ` c.c.c.c.r                             1 c.c.c.c.7.                      ;.c.c.c.c.W                                                   X > 0.c.c.c.c.c.c.c.c.e.-...} ^ ^ ^ / / | c.c.c.c.t.                L c.c.c.c.5.                                      s.c.c.c.c.= .               ",
"                      g z.c.c.c.c.c.c.s.1.@.*.5.x.c.c.c.c.c.c.`                   g c.c.c.c.U                               > c.c.c.c.7.                      #.c.c.c.c.^                                                   = a.c.c.c.c.c.h.! i o   .   .   . .   . 3 c.c.c.c.t.                J c.c.c.c.8.                                    . s.c.c.c.c.- X               ",
"                        p a.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.z.H .                   q.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c./       . X.c.c.c.c.] . .                                             . *.c.c.c.c.c.O.&                         3 c.c.c.c.e.                D c.c.c.c.t.                                    . x.c.c.c.c.- .               ",
"                        . % / c.c.c.c.c.c.c.c.c.c.c.c.z...1 . .                   i.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c./         ] c.c.c.c.*.X                                               i c.c.c.c.c....                           6 c.c.c.c.t.                v c.c.c.c.h.                                    . c.c.c.c.c.- .               ",
"                          6 7.c.c.c.t.6.p.z.h.t.2.` m %                           i.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.^         H c.c.c.c.q.                                                [ c.c.c.c.a.#                             r c.c.c.c.t.                i c.c.c.c.c.*                                   - c.c.c.c.c.- .               ",
"                        s l.c.c.c.Y O                                         . X r.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c./       . g c.c.c.c.c.&                                               y.c.c.c.c.!                               j c.c.c.c.e.                - c.c.c.c.c.i                                   a c.c.c.c.c.-                 ",
"                      8 z.c.c.c.J                                                 U / ^ / / ! / / / / / / / / / ^ ^ ^ ^ ^ / | c.c.c.c.s.^ / / ! / / k         * c.c.c.c.c.m                                             . x.c.c.c.c.k                               U c.c.c.c.t.                  s.c.c.c.c.U .                                 J c.c.c.c.c.- .               ",
"                      *.c.c.c.r.X                                                   .     .       .                 . .   . > c.c.c.c.7.    .     .             6.c.c.c.c.*.                                            * c.c.c.c.c.r                               1.c.c.c.c.t.                  O.c.c.c.c.q..                                 2.c.c.c.c.c.-                 ",
"                    O c.c.c.c.o.                                                                                            > c.c.c.c.7.                        P c.c.c.c.c.q .                                         + c.c.c.c.c.a                             q c.c.c.c.c.t.                  m c.c.c.c.c.t                             . > c.c.c.c.c.c.: .               ",
"                    - c.c.c.c.3.                                                                                            > c.c.c.c.7.                        * z.c.c.c.c.5.X                                         . k.c.c.c.c.H                           . >.c.c.c.c.c.r.                X + k.c.c.c.c.4..                             O.c.c.c.c.c.c.-                 ",
"                    . z.c.c.c.c.` -   .   .           . . .   .                                                             > c.c.c.c.7.                          Q c.c.c.c.c.X.X                                         1.c.c.c.c.5..                         ] c.c.c.c.c.c.t.                .   ! c.c.c.c.c.Y                           v c.c.c.c.c.c.c.- .               ",
"                      [ c.c.c.c.c.c.t.,.*.*.&.*.*.*.#...] I g -                                                             > c.c.c.c.7.                          # p.c.c.c.c.c.;.-   .                   # B r         . L c.c.c.c.c.I                     = #.c.c.c.c.c.c.c.t.                    % g.c.c.c.c.c.Y O               . . . N c.c.c.c.c.c.c.c.- .               ",
"                      * 0.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.,.x .                                                       1 c.c.c.c.7.                            r z.c.c.c.c.c.z.] p $ .       % u H ;.z.c.z           * k.c.c.c.c.c.X.3         X X 6 Q h.c.c.c.F -.c.c.c.t.                      x c.c.c.c.c.c.8.b + .       . * x 5.c.c.c.>.:.c.c.c.c.- .               ",
"                        = #.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.>.-                                                     > c.c.c.c.7.                              k z.c.c.c.c.c.c.c.c.h.p.h.c.c.c.c.c.c.c.z           . L c.c.c.c.c.c.c.0.O.[ ..;.s.c.c.c.c.c.Q   Y c.c.c.t.                        U c.c.c.c.c.c.c.c.q.,.*.2.r.c.c.c.c.c.r.* W c.c.c.c.- .               ",
"                      - I 3.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.q.=                                                   > c.c.c.c.7.                                u p.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.z             . ..c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.U . . x c.c.c.r.                          J c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.0.-   m c.c.c.c.- .               ",
"                  + / x.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.*.                                                  1 c.c.c.c.7.                                  # ` z.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.i             . X Y c.c.c.c.c.c.c.c.c.c.c.c.c.i.g       1 c.c.c.r.                            t 9.c.c.c.c.c.c.c.c.c.c.c.c.c.] +     r c.c.c.c.- .               ",
"                * 7.c.c.c.c.h.` f - +           . . + > r F 2.c.c.c.c.c.c.u                                                 > c.c.c.c.7.                                      % J 2.c.c.c.c.c.c.c.c.c.c.2.L *                     1 ] h.c.c.c.c.c.c.c.c.6.A +         . h.c.c.e.                            . X v ;.c.c.c.c.c.c.c.c.h.[ 6         + c.c.c.c.- .               ",
"              O 5.c.c.c.c.#.*   .               .     .       Z c.c.c.c.c.`                                                 .                                                       + r m D K H B v 9 +                           . . . 0 v G J D m i #                                                     . .     O t m G K A z 8 .                       . .               ",
"              Y c.c.c.c.:.O                     .               ..c.c.c.c.9.                                                                                                                                                                                                                                                                                                  ",
"            + h.c.c.c.c.6                                       s c.c.c.c.h.                                                                                                                                                                                                                                                                                                  ",
"            s c.c.c.c.3.                                        3 c.c.c.c.c.                                                                                                                                                                                                                                                                                                  ",
"            H c.c.c.c...                                        5 c.c.c.c.h.                                                                                                                                                                                                                                                                                                  ",
"            Y c.c.c.c.`                                         x c.c.c.c.6.                                                                                                                                                                                                                                                                                                  ",
"            D c.c.c.c.+.                                        #.c.c.c.c./                                                                                                                                                                                                                                                                                                   ",
"            j c.c.c.c.l.+ .                                   x c.c.c.c.c.r                                                                                                                                                                                                                                                                                                   ",
"            + k.c.c.c.c.| .                                 b z.c.c.c.c.,.                                                                                                                                                                                                                                                                                                    ",
"              ] c.c.c.c.c.+.* .                         w #.c.c.c.c.c.h.1 .                                                                                                                                                                                                                                                                                                   ",
"              # i.c.c.c.c.c.z...v 6 +     . X * 0 v / q.c.c.c.c.c.c.k.f                                                                                                                                                                                                                                                                                                       ",
"                6 i.c.c.c.c.c.c.c.c.c.c.k.z.c.c.c.c.c.c.c.c.c.c.c.t.r .                                                                                                                                                                                                                                                                                                       ",
"                . - ;.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.k.W +                                                                                                                                                                                                                                                                                                           ",
"                      a :.x.c.c.c.c.c.c.c.c.c.c.c.c.c.c.c.4.D %                                                                                                                                                                                                                                                                                                               ",
"                          % b Q *.q.a.k.c.l.h.t.2.X.I k *                                                                                                                                                                                                                                                                                                                     ",
"                                .                                                                                                                                                                                                                                                                                                                                             ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              ",
"                                                                                                                                                                                                                                                                                                                                                                              "
}; 
"""
    def Initialize(self):
        import plugin_init
        self.list = [
            "import", "export", "add_world", "add_box", "add_sphere",
            "add_cylinder", "add_cone", "set_material", "set_precision",
            "set_physical_volume", "hide_parts", "filter_parts",
            "show_measurements", "manage_materials"
        ]
        self.appendToolbar("g4cad", self.list)
        self.appendMenu("g4cad", self.list)

    def Activated(self):
        if not (FreeCAD.ActiveDocument):
            FreeCAD.newDocument()
        FreeCAD.Console.PrintMessage('g4cad workbench loaded.. \n')
        return

    def Deactivated(self):
        return

    def ContextMenu(self, recipient):
        self.appendContextMenu(MenuText, self.list)

    def GetClassName(self):
        return "Gui::PythonWorkbench"


Gui.addWorkbench(GDML)
App.addImportType("Geometry Description Markup Language(*.gdml)",
                  "GdmlImporter")
App.addExportType("Geometry Description Markup Language(*.gdml)",
                  "GdmlExporter")
